# Generated by Django 4.1.7 on 2023-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendenc_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendenc',
            name='date_time',
        ),
        migrations.AddField(
            model_name='attendenc',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendenc',
            name='entry_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendenc',
            name='exit_time',
            field=models.TimeField(null=True),
        ),
    ]
